# Generated by Django 4.2.2 on 2023-06-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Introduction to Mocha Testing Framework.jpg', upload_to='images'),
        ),
    ]
